version: "3.8"

services:
  app:
    container_name: data-analysis-frontend-dev
    image: data-analysis-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    # volumes:
    #   - ./src:/app/src
    ports:
      - 3026:3000
    environment:
      - WATCHPACK_POLLING=true
