export default {
  FORCE_RETIREMENT: "FORCE_RETIREMENT",
  DISABILITY: "DISABILITY",
  DEATH_RETIREMENT: "DEATH_RETIREMENT",
  AUTO_RETIREMENT: "AUTO_RETIREMENT",
  EARLY_RETIREMENT: "EARLY_RETIREMENT",
};
