export default {
  NONE: "NONE",
  REVIEW_PENDING: "REVIEW_PENDING",
  APPROVED: "APPROVED",
  CANCELLED: "CANCELLED",
  ON_HOLD: "ON_HOLD",
  REVIEW_FORWARD: "REVIEW_FORWARD",
  REVIEW_BACKWARD: "REVIEW_BACKWARD",
  BACK_TO_APPLICANT: "BACK_TO_APPLICANT",
};
